name: event_calendar
description: A flutter package to create local events non reliant on a device's local calendar system.
version: 0.0.5
author: BillyBonk
homepage: https://github.com/bbonk4/EventCalendar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


